# Generated by Django 5.1.1 on 2024-09-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='filepond',
        ),
    ]
