# Generated by Django 5.1.1 on 2024-09-18 22:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_video_video_filepond'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepond', models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm'])])),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='filepond',
        ),
        migrations.AddField(
            model_name='video',
            name='videofile',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='video', to='videos.videofile'),
            preserve_default=False,
        ),
    ]
