# Generated by Django 5.1.1 on 2024-09-18 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_photos_eventimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 20, 24, 2, 638967)),
            preserve_default=False,
        ),
    ]
