# Generated by Django 5.1.1 on 2024-09-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_eventimages_eventimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimage',
            old_name='image',
            new_name='filepond',
        ),
    ]
