# Generated by Django 5.1.1 on 2024-09-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='volunteers_needed',
            field=models.IntegerField(default=0),
        ),
    ]
