# Generated by Django 5.1.1 on 2024-09-19 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organizationdocument_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
    ]
